apiVersion: v1
kind: Service
metadata:
  name: tasks-service
spec:
  selector:
    app: task
  type: LoadBalancer
  ports:
    - protocol: TCP
    #outside world
      port: 80
    # port we are listening on
      targetPort: 3000

#Configuring the deployment     
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task
  template:
    metadata:
      labels:
        app: task
    #configuring the pod
    spec:
      containers:
        - name: tasks-api
          image: MY PUSHED IMAGE 
          env:
              - name: MONGODB_CONNECTION_URI
                value: 'MY MONGO URI'
              - name: AUTH_API_ADDRESS
                value: 'auth-service.default:3000'
