apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
# pod
  template: 
    metadata:
      labels:
        app: frontend
# container
    spec:
      containers:
        - name: frontend
        # k8's will always pull the latest, alternative to tags or pull policy
          image: cfech/kub-225-frontend:latest          