apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task
# pod
  template: 
    metadata:
      labels:
        app: task
# container
    spec:
      containers:
        - name: task
        # k8's will always pull the latest, alternative to tags or pull policy
          image: cfech/kub-225-task-app:latest
          env:
            - name: AUTH_ADDRESS
            # localhost is only for our container in the same pod
              # value: localhost
              # for pod to pod communication must give the ip of the service for the other pod - 231
              # value: 10.106.104.92
              # 232 -  utilizing coredns to pass in a the domain name of the other pod to the app , just have to pass in the "[service name.namespace]"
              value: "auth-service.default"
            - name: TASKS_FOLDER
              value: tasks