FROM python

WORKDIR /app

COPY . /app

CMD [ "python", "bmi.py" ]

#docker build -t ass1python .

#if we wanted to restart the python app should have the -i and -a flags so it is attatched and interactive

#will run conatainer based on image, close it an it is removed
#docker run -it --rm --name ass1pc -t ass1python