# see 186_first_Kubernetes\deployment.yml for more info

apiVersion: apps/v1
kind: Deployment
metadata:
  name: volumes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-story-volume
  #pod template
  template:
    metadata:
      labels:
        app: k8s-story-volume
    spec:
      containers:
        - name: volume-story
          image: cfech/k8s-volume:2
          # configuring environment variable that will be passed into our container
          env:
            - name: STORY_FOLDER
              # value: 'story'
              # example configuring with configMap
              valueFrom:
                configMapKeyRef: 
                # from config map file env.yml
                  name: env-config-map
                  # also from env.yml, will pull the value from this key and set it to the story folder env var
                  key: folder
          # imagePullPolicy: Always
          #defining where the available volumes should be mounted
          volumeMounts: 
          # path inside of the container that holds the data we want to be saved, where the directory should be mounted, this path is also defined in the docker.compose.yml
            - mountPath: /app/story
            # could have multiple volumes available to us so we define the name of the one we want to be using
              name: story-volume
      #defining the volume that is part of the pod, all the containers in the pod can then use these volumes
      volumes:
        - name: story-volume
        #applies a claim to a persistent volume
          persistentVolumeClaim:
          # from host-pvc.yml
            claimName: host-pvc